version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk 
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            gradle test
            gradle jar
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: /code/artifact
          destination: prefix
