version: 2.0
jobs:
    test:
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            - checkout
            - run:
                  name: Gradle Test
                  command:
                      gradle test
            - store_test_results:
                  path: build/test-results
            - persist_to_workspace:
                root: .
                paths:
                    - .
    package:
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            - attach_workspace:
                at: .
            - run:
                name: Gradle Jar
                command:
                    gradle jar
            - store_artifacts:
                path: build/libs
                destination: prefix\
            - persist_to_workspace:
                  root: build/libs
                  paths:
                      - .
    dockerize:
      machine: true
      steps:
      - attach_workspace:
          at: .
      - checkout
      # Login to docker
      - run: docker login -u kseniapyagay -p 123456789ksu

      # build the application image
      - run: docker build -t kseniapyagay/myapp:$CIRCLE_SHA1 .

      # deploy the image
      - run: docker push kseniapyagay/myapp:$CIRCLE_SHA1
workflows:
    version: 2
    two_job_flow:
        jobs:
            - test
            - package:
                  requires:
                      - test
            - dockerize:
                  requires:
                      - package